### ISSUE TITLE
Debian/Linux install script issues

### ISSUE THREAD

**Issue by ingoha** [sanjayseshan/spikeprime-tools#5]
1.) The install script installs python < 3.7 on certain systems
2.) It is considered bad practice to install python libraries system-wide via sudo pip install.
Fix for 2. is using a virtual environment.
More effort is required for 1....

**Comment by sanjayseshan** [comment]
Thank you for the feedback.

1) I wasn't aware that it didn't work on older python versions. I think that `sudo apt-get install python3.7` would fix this.
2) I am not too experienced with using virtual environments. This install script was to get everything to work so that a VS Code extension (https://github.com/sanjayseshan/spikeprime-vscode) could call the script. I will look at your pull request and also make sure that the extension would still work.
